### PR TITLE
Dockerfile.example: import source before depsolve

### PR DESCRIPTION
**Pull request by codificat**
Updating the order of commands in `Dockerfile.example`: if we invoke the `assemble` script during docker build the playbook should be imported first so that e.g. a `requirements.txt` in the repo is copied.

Also, in this case we must copy to `/tmp/src` instead of `${APP_HOME}`, as this is where `assemble` expects it.

### CODE REVIEW

**Review by aweiteka — CHANGES_REQUESTED** [review]
I would prefer we simplify this example. The user is left with a choice on if to use the assemble script, not knowing the benefit. How about uncomment the assemble script and have them put the playbooks in `/tmp/src`? Simple and the documented build opts are available to them. The only cost is another (possibly unnecessary) layer.

**Comment by codificat** [comment]
Ok, yes, I see your point.

Maybe provide two `Dockerfile` examples? Both simple, one using the s2i/`assemble` approach and one without it, and update the docs a bit explaining the rationale behind each approach.

I mean: the example was simple before we started to add things that are handled by `assemble`; we can keep the simple one and provide another (simple) that has everything set to invoke `assemble`, and we explain why in the docs.

**Comment by aweiteka** [comment]
> Maybe provide two Dockerfile examples? Both simple, one using the s2i/assemble approach and one without it

That could work. They'll need to open both, read top-level comment block, then decide which one.

1. **Dockerfile.simple**: "I just need to package my playbooks."
1. **Dockerfile.advanced**: "I have to install some python module dependencies or install the `oc` client."

**Comment by codificat** [comment]
Ok, moved `Dockerfile.example` to the two versions (simple and advanced). Squashed and rebased.

**Review by aweiteka — APPROVED** [review]

**Pull request merged**
