### PR TITLE
[WIP] Jenkins - updates, S2I and test-app run

### PR DESCRIPTION
**Pull request by jcpowermac**
Adds update from [ojalloy](https://github.com/jcpowermac/ojalloy) project:
- Use GitHub SDK
- The ability to test multiple Dockerfile in various directories
- Configurations of Jenkins:
  - URL
  - ConfigMap -> Job parameters
- Utils and DSL updates

Adds the ability to build S2I from the `test/test-app` Ansible playbook and
start it within a pod.

### CODE REVIEW

**Review by aweiteka — COMMENTED** [review]
why do we need the openshift-client plugin in this repo?

**Comment by aweiteka** [comment]
The `vars/` dir seems more like `methods/`. Is this a typical way to organize?

**Comment by aweiteka** [comment]
I wonder if we could organize it like this:

`jenkins_master`: Jenkins master configuration
`pipeline`: Jenkinsfile, groovy methods, etc.

Maybe the Jenkinsfile should remain in the root of the project.

**Comment by jcpowermac** [comment]
@aweiteka maybe instead of this PR we really should do this instead:
- Move (and rename ;-) ) the [ojalloy](https://github.com/jcpowermac/ojalloy) project out of my organization.  Maybe [rhsyseng](https://github.com/RHsyseng/) org?
- Pull the Jenkins specific code out of this repo except for the Jenkinsfile - that needs to be in the project.
- Add the ConfigMap and modified pipeline to the OpenShift project and reconfigure.

What do you think?

The organization of folders for the libraries are static as far as I know ... take a look at: 
https://jenkins.io/doc/book/pipeline/shared-libraries/#directory-structure

**Comment by aweiteka** [comment]
> Move (and rename ;-) ) the ojalloy project out of my organization. Maybe rhsyseng org?

yes

> Pull the Jenkins specific code out of this repo except for the Jenkinsfile - that needs to be in the project.

yes

> Add the ConfigMap and modified pipeline to the OpenShift project and reconfigure.

I don't follow this recommendation but it's probably consistent with the above refactoring.

> 
> What do you think?
> 
> The organization of folders for the libraries are static as far as I know ... take a look at:
> https://jenkins.io/doc/book/pipeline/shared-libraries/#directory-structure

We'll just follow this then. We can't fix java on our own. :)

**Comment by jcpowermac** [comment]
Closing this for now.  Will reopen with suggested changes.

**Pull request closed without merging**
